var hierarchy =
[
    [ "com.javicodema.entities.Assist", "classcom_1_1javicodema_1_1entities_1_1_assist.html", null ],
    [ "com.javicodema.entities.Card", "classcom_1_1javicodema_1_1entities_1_1_card.html", null ],
    [ "com.javicodema.dtos.CardDTO", "classcom_1_1javicodema_1_1dtos_1_1_card_d_t_o.html", null ],
    [ "com.javicodema.entities.Club", "classcom_1_1javicodema_1_1entities_1_1_club.html", null ],
    [ "com.javicodema.controllers.ClubController", "classcom_1_1javicodema_1_1controllers_1_1_club_controller.html", null ],
    [ "com.javicodema.dtos.ClubDTO", "classcom_1_1javicodema_1_1dtos_1_1_club_d_t_o.html", null ],
    [ "com.javicodema.services.ClubService", "classcom_1_1javicodema_1_1services_1_1_club_service.html", null ],
    [ "com.javicodema.firebaseAuth.FirebaseCondition", "interfacecom_1_1javicodema_1_1firebase_auth_1_1_firebase_condition.html", null ],
    [ "com.javicodema.FirebaseConfig", "classcom_1_1javicodema_1_1_firebase_config.html", null ],
    [ "com.javicodema.services.FirebaseService", "classcom_1_1javicodema_1_1services_1_1_firebase_service.html", null ],
    [ "com.javicodema.entities.Game", "classcom_1_1javicodema_1_1entities_1_1_game.html", null ],
    [ "com.javicodema.controllers.GameController", "classcom_1_1javicodema_1_1controllers_1_1_game_controller.html", null ],
    [ "com.javicodema.dtos.GameDTO", "classcom_1_1javicodema_1_1dtos_1_1_game_d_t_o.html", null ],
    [ "com.javicodema.entities.enums.GameResult", "enumcom_1_1javicodema_1_1entities_1_1enums_1_1_game_result.html", null ],
    [ "com.javicodema.services.GameService", "classcom_1_1javicodema_1_1services_1_1_game_service.html", null ],
    [ "com.javicodema.entities.GamesPlayed", "classcom_1_1javicodema_1_1entities_1_1_games_played.html", null ],
    [ "com.javicodema.services.GamesPlayedService", "classcom_1_1javicodema_1_1services_1_1_games_played_service.html", null ],
    [ "com.javicodema.entities.enums.GameState", "enumcom_1_1javicodema_1_1entities_1_1enums_1_1_game_state.html", null ],
    [ "com.javicodema.entities.Goal", "classcom_1_1javicodema_1_1entities_1_1_goal.html", null ],
    [ "com.javicodema.dtos.GoalDTO", "classcom_1_1javicodema_1_1dtos_1_1_goal_d_t_o.html", null ],
    [ "com.javicodema.services.InsertSampleDataService", "classcom_1_1javicodema_1_1services_1_1_insert_sample_data_service.html", null ],
    [ "com.javicodema.dtos.LoginDTO", "classcom_1_1javicodema_1_1dtos_1_1_login_d_t_o.html", null ],
    [ "com.javicodema.MessageCreator", "classcom_1_1javicodema_1_1_message_creator.html", null ],
    [ "com.javicodema.dtos.MessageDTO", "classcom_1_1javicodema_1_1dtos_1_1_message_d_t_o.html", null ],
    [ "com.javicodema.entities.Petition", "classcom_1_1javicodema_1_1entities_1_1_petition.html", null ],
    [ "com.javicodema.dtos.PetitionDTO", "classcom_1_1javicodema_1_1dtos_1_1_petition_d_t_o.html", null ],
    [ "com.javicodema.services.PetitionService", "classcom_1_1javicodema_1_1services_1_1_petition_service.html", null ],
    [ "com.javicodema.entities.enums.PetitionState", "enumcom_1_1javicodema_1_1entities_1_1enums_1_1_petition_state.html", null ],
    [ "com.javicodema.entities.Player", "classcom_1_1javicodema_1_1entities_1_1_player.html", null ],
    [ "com.javicodema.controllers.PlayerController", "classcom_1_1javicodema_1_1controllers_1_1_player_controller.html", null ],
    [ "com.javicodema.dtos.PlayerDTO", "classcom_1_1javicodema_1_1dtos_1_1_player_d_t_o.html", null ],
    [ "com.javicodema.services.PlayerService", "classcom_1_1javicodema_1_1services_1_1_player_service.html", null ],
    [ "com.javicodema.Responses", "classcom_1_1javicodema_1_1_responses.html", null ],
    [ "com.javicodema.entities.Rival", "classcom_1_1javicodema_1_1entities_1_1_rival.html", null ],
    [ "com.javicodema.controllers.RivalController", "classcom_1_1javicodema_1_1controllers_1_1_rival_controller.html", null ],
    [ "com.javicodema.dtos.RivalDTO", "classcom_1_1javicodema_1_1dtos_1_1_rival_d_t_o.html", null ],
    [ "com.javicodema.services.RivalService", "classcom_1_1javicodema_1_1services_1_1_rival_service.html", null ],
    [ "com.javicodema.services.RolesService", "classcom_1_1javicodema_1_1services_1_1_roles_service.html", null ],
    [ "com.javicodema.services.SecurityService", "classcom_1_1javicodema_1_1services_1_1_security_service.html", null ],
    [ "com.javicodema.dtos.SettingsDTO", "classcom_1_1javicodema_1_1dtos_1_1_settings_d_t_o.html", null ],
    [ "com.javicodema.SoccerStatsWebApplication", "classcom_1_1javicodema_1_1_soccer_stats_web_application.html", null ],
    [ "com.javicodema.dtos.SubsDTO", "classcom_1_1javicodema_1_1dtos_1_1_subs_d_t_o.html", null ],
    [ "com.javicodema.entities.Substitution", "classcom_1_1javicodema_1_1entities_1_1_substitution.html", null ],
    [ "com.javicodema.entities.Team", "classcom_1_1javicodema_1_1entities_1_1_team.html", null ],
    [ "com.javicodema.controllers.TeamController", "classcom_1_1javicodema_1_1controllers_1_1_team_controller.html", null ],
    [ "com.javicodema.dtos.TeamDTO", "classcom_1_1javicodema_1_1dtos_1_1_team_d_t_o.html", null ],
    [ "com.javicodema.entities.TeamsAllowed", "classcom_1_1javicodema_1_1entities_1_1_teams_allowed.html", null ],
    [ "com.javicodema.services.TeamsAllowedService", "classcom_1_1javicodema_1_1services_1_1_teams_allowed_service.html", null ],
    [ "com.javicodema.services.TeamService", "classcom_1_1javicodema_1_1services_1_1_team_service.html", null ],
    [ "com.javicodema.entities.TeamsInto", "classcom_1_1javicodema_1_1entities_1_1_teams_into.html", null ],
    [ "com.javicodema.services.TeamsIntoService", "classcom_1_1javicodema_1_1services_1_1_teams_into_service.html", null ],
    [ "com.javicodema.entities.Training", "classcom_1_1javicodema_1_1entities_1_1_training.html", null ],
    [ "com.javicodema.controllers.TrainingController", "classcom_1_1javicodema_1_1controllers_1_1_training_controller.html", null ],
    [ "com.javicodema.dtos.TrainingDTO", "classcom_1_1javicodema_1_1dtos_1_1_training_d_t_o.html", null ],
    [ "com.javicodema.services.TrainingService", "classcom_1_1javicodema_1_1services_1_1_training_service.html", null ],
    [ "com.javicodema.entities.User", "classcom_1_1javicodema_1_1entities_1_1_user.html", null ],
    [ "com.javicodema.controllers.UserController", "classcom_1_1javicodema_1_1controllers_1_1_user_controller.html", null ],
    [ "com.javicodema.services.UserService", "classcom_1_1javicodema_1_1services_1_1_user_service.html", null ],
    [ "Comparator", null, [
      [ "com.javicodema.AssistComparator", "classcom_1_1javicodema_1_1_assist_comparator.html", null ],
      [ "com.javicodema.ScoredComparator", "classcom_1_1javicodema_1_1_scored_comparator.html", null ],
      [ "com.javicodema.SubsComparator", "classcom_1_1javicodema_1_1_subs_comparator.html", null ]
    ] ],
    [ "Condition", null, [
      [ "com.javicodema.firebaseAuth.FirebaseConditionImpl", "classcom_1_1javicodema_1_1firebase_auth_1_1_firebase_condition_impl.html", null ]
    ] ],
    [ "CrudRepository", null, [
      [ "com.javicodema.repositories.AssistRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_assist_repository.html", null ],
      [ "com.javicodema.repositories.CardRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_card_repository.html", null ],
      [ "com.javicodema.repositories.ClubRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_club_repository.html", null ],
      [ "com.javicodema.repositories.GameRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_game_repository.html", null ],
      [ "com.javicodema.repositories.GamesPlayedRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_games_played_repository.html", null ],
      [ "com.javicodema.repositories.GoalRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_goal_repository.html", null ],
      [ "com.javicodema.repositories.PetitionRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_petition_repository.html", null ],
      [ "com.javicodema.repositories.PlayerRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_player_repository.html", null ],
      [ "com.javicodema.repositories.RivalRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_rival_repository.html", null ],
      [ "com.javicodema.repositories.SubstitutionRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_substitution_repository.html", null ],
      [ "com.javicodema.repositories.TeamRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_team_repository.html", null ],
      [ "com.javicodema.repositories.TeamsAllowedRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_teams_allowed_repository.html", null ],
      [ "com.javicodema.repositories.TeamsIntoRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_teams_into_repository.html", null ],
      [ "com.javicodema.repositories.TrainingRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_training_repository.html", null ],
      [ "com.javicodema.repositories.UsersRepository", "interfacecom_1_1javicodema_1_1repositories_1_1_users_repository.html", null ]
    ] ],
    [ "JsonSerializer", null, [
      [ "com.javicodema.jsonSerializer.GameSerializer< T >", "classcom_1_1javicodema_1_1json_serializer_1_1_game_serializer.html", null ],
      [ "com.javicodema.jsonSerializer.TeamSerializer< T >", "classcom_1_1javicodema_1_1json_serializer_1_1_team_serializer.html", null ],
      [ "com.javicodema.jsonSerializer.TeamStatsSerializer< T >", "classcom_1_1javicodema_1_1json_serializer_1_1_team_stats_serializer.html", null ],
      [ "com.javicodema.jsonSerializer.TrainingSerializer< T >", "classcom_1_1javicodema_1_1json_serializer_1_1_training_serializer.html", null ],
      [ "com.javicodema.jsonSerializer.UserSerializer< T >", "classcom_1_1javicodema_1_1json_serializer_1_1_user_serializer.html", null ]
    ] ],
    [ "Serializable", null, [
      [ "com.javicodema.entities.compositeIds.GamesPlayedId", "classcom_1_1javicodema_1_1entities_1_1composite_ids_1_1_games_played_id.html", null ],
      [ "com.javicodema.entities.compositeIds.TeamsAllowedId", "classcom_1_1javicodema_1_1entities_1_1composite_ids_1_1_teams_allowed_id.html", null ],
      [ "com.javicodema.entities.compositeIds.TeamsIntoId", "classcom_1_1javicodema_1_1entities_1_1composite_ids_1_1_teams_into_id.html", null ]
    ] ],
    [ "UserDetailsService", null, [
      [ "com.javicodema.services.UserDetailsServiceImpl", "classcom_1_1javicodema_1_1services_1_1_user_details_service_impl.html", null ]
    ] ],
    [ "WebSecurityConfigurerAdapter", null, [
      [ "com.javicodema.WebSecurityConfig", "classcom_1_1javicodema_1_1_web_security_config.html", null ]
    ] ]
];